podtwo: run mirror.freifunk.dev website

diff --git a/locations/podtwo.yml b/locations/podtwo.yml
--- a/locations/podtwo.yml
+++ b/locations/podtwo.yml
@@ -16,18 +16,59 @@ hosts:
   # eth0: 2.5G RTL8125B from mainboard
   - hostname: podtwo
     role: corerouter
-    openwrt_version: snapshot
+    openwrt_version: 24.10-SNAPSHOT
     model: "x86-64"
     image_search_pattern: "*-ext4-combined-efi.img*"
     imagebuilder_config:
       CONFIG_TARGET_ROOTFS_PARTSIZE: 256
       CONFIG_GRUB_BOOTOPTS: "usb_storage.quirks=152d:0583:ut"
     host__packages__to_merge:
-      - bash rsync screen tmux htop mtr
-      - parted fdisk e2fsprogs btrfs-progs losetup resize2fs coreutils-shred
+      - bash rsync screen tmux htop mtr git git-http curl jq
+      - parted fdisk e2fsprogs btrfs-progs losetup resize2fs coreutils-shred blkid
       - podman conmon crun catatonit netavark external-protocol
     host__rclocal__to_merge:
       - "sed -i 's|#firewall_driver|firewall_driver|g' /etc/containers/containers.conf"
+      - "/etc/init.d/mirror enable ; /etc/init.d/mirror start"
+    host__files__to_merge:
+      - path: /etc/init.d/mirror
+        mode: '0755'
+        content: |
+          #!/bin/sh /etc/rc.common
+          USE_PROCD=1
+          START=99
+          STOP=1
+          diskuuid="95e5aef4-736b-4860-90e3-2eceeaf43c55"
+          mountpoint="/mnt/mirror"
+          image="docker.io/library/caddy:latest"
+          name="mirror"
+          ip6="2001:bf7:820:3402::2"
+          ip4="10.248.33.74"
+          dns="10.248.33.73"
+          boot() {
+            if ! mount | grep $mountpoint >/dev/null ; then
+              mkdir -p $mountpoint ; mount $(blkid -U $diskuuid) $mountpoint
+            fi
+            mkdir -p $mountpoint/config $mountpoint/data $mountpoint/www
+          }
+          # TODO: mount readonly
+          start_service() {
+            podman pull -q --retry=3 --retry-delay=5s $image || true
+            procd_open_instance
+            procd_set_param command /usr/bin/podman run --rm -i \
+              --ip6 $ip6 --ip $ip4 --dns $dns --no-hosts \
+              -v $mountpoint/config:/etc/caddy \
+              -v $mountpoint/data:/data \
+              -v $mountpoint/www:/www \
+              --name $name $image
+            procd_set_param respawn 60 10 0  # respawn indefinitely, wait 10s before retry
+            procd_set_param stdout 1
+            procd_set_param stderr 1
+            procd_close_instance
+          }
+          # TODO: umount
+          stop_service() {
+            podman kill $name
+          }
 
 # 10.248.33.64/27 - pktpls+bbb@systemli.org
 # - 10.248.33.64/29 - mgmt
@@ -52,13 +93,11 @@ networks:
     assignments:
       podtwo: 1
 
-  - vid: 43
-    untagged: true
+  - role: podman
     ifname: podman0
-    name: podman
-    role: ext
+    untagged: true
+    inbound_filtering: true
     prefix: 10.248.33.72/29
     ipv6_subprefix: 2
     assignments:
-      podtwo-core: 1
       mirror: 2
